---
- name: Build AD for LDAP
  hosts: samba-server
  become: true
  vars:
    - enable_dhcp_services: false
    - samba_create_domain_controller: true
    - samba_create_domain_users: true  #defines if users defined in samba_domain_users list should be created
    - samba_domain_users:
        - name: 'gerrit'
          password: 'P@55w0rd'
        - name: 'gitlab'
          password: 'P@55w0rd'
        - name: 'lab'
          password: 'P@55w0rd'
    - samba_server_role: 'active directory domain controller'  #defines server role...(standalone server or active directory domain controller)
  roles:
    - role: ansible-isc-dhcp
      when: enable_dhcp_services is defined and enable_dhcp_services
    - role: ansible-ntp
    - role: ansible-samba
  tasks:

- name: Installs Gerrit Code Review
  hosts: gerrit-server
  become: true
  vars:
    - gerrit_allow_remote_admin: true  #defines if gerrit should allow remote admin capabilities
    - gerrit_replication_enabled: true
    - gerrit_auth_type: LDAP_BIND  #defines authorization type...OPENID, LDAP, LDAP_BIND...
    - gerrit_db_info:
#        - host: localhost
#          type: h2
#          db: db/ReviewDB
#          user: gerrit
#          pass: gerrit
        - host: localhost
          type: mysql
          db: reviewdb
          user: gerrit
          pass: gerrit
    - gerrit_ldap_info:
        - server: 'ldap://192.168.202.200'
          accountbase: 'DC=example,DC=org'
          accountpattern: '(&(objectClass=person)(userPrincipalName=${username}))'
          accountscope: 'sub'
          groupbase: 'DC=example,DC=org'
          accountfullname: 'displayName'
          accountmemberfield: 'memberOf'
          accountemailaddress: 'mail'
          accountsshusername: '${sAMAccountName.toLowerCase}'
          referral: 'follow'
    - gerrit_vagrant_install: true
    - install_mysql: true
  roles:
    - role: ansible-apache2
    - role: ansible-mariadb-mysql
      when: install_mysql is defined and install_mysql
    - role: ansible-gerrit
  tasks:

- name: Installs Jenkins
  hosts: jenkins-server
  become: true
  vars:
  roles:
    - role: ansible-jenkins
  tasks:

- name: Installs Gitlab-CE
  hosts: gitlab-server
  become: true
  vars:
  roles:
    - role: ansible-postfix
    - role: ansible-gitlab-ce
  tasks:

- name: Update /etc/hosts
  hosts: all
  remote_user: vagrant
  become: true
  vars:
  roles:
  tasks:
    - name: updating /etc/hosts
      lineinfile:
        dest: /etc/hosts
        regexp: ".*{{ item }}$"
        line: "{{ hostvars[item].ansible_ssh_host }} {{ item }}"
        state: present
      with_items: groups['all']
