---
- src: https://github.com/mrlesmithjr/ansible-apache2.git
- src: https://github.com/mrlesmithjr/ansible-gerrit.git
- src: https://github.com/mrlesmithjr/ansible-gitlab-ce.git
- src: https://github.com/mrlesmithjr/ansible-jenkins.git
- src: https://github.com/mrlesmithjr/ansible-mariadb-mysql.git
- src: https://github.com/mrlesmithjr/ansible-postfix.git
