---
- name: Updates all packages to latest
  hosts: all
  remote_user: vagrant
  become: true
  vars:
  roles:
  tasks:
    - name: Updating packages
      apt:
        cache_valid_time: 3
        update_cache: true
        upgrade: safe

    - name: cleaning up
      command: "{{ item }}"
      with_items:
        - 'apt-get -y autoclean'
